name: build-and-push
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: taltiko
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # FE
      - name: Build & Push FE
        uses: docker/build-push-action@v6
        with:
          context: ./FE
          file: ./FE/Dockerfile
          push: true
          tags: taltiko/shotten-fe:latest

      # BE
      - name: Build & Push BE
        uses: docker/build-push-action@v6
        with:
          context: ./BE
          file: ./BE/Dockerfile
          push: true
          tags: taltiko/shotten-be:latest